### PR TITLE
Update description of available languages for numpy.org

### PR DESCRIPTION
**Pull request by melissawm**

### CODE REVIEW

**Comment by steppi** [comment]
Thanks for catching this @melissawm. That’s an embarrassing mistake on my part. l guess a result of revising the text of that card dozens of times until I was no longer processing the text.

**Comment by melissawm** [comment]
Is there a manual step for pages build and deployment? It looks like it was not triggered by this pr...

**Comment by steppi** [comment]
> Is there a manual step for pages build and deployment? It looks like it was not triggered by this pr...

Ah, sorry. I forgot that deployment is still manual. I'll manually deploy and look into getting automatic deployment set up.

**Comment by steppi** [comment]
It's up now https://scientific-python-translations.github.io/

**Pull request merged**
